### ISSUE TITLE
DACTE: Implementações dos Modais

### ISSUE THREAD

**Issue by CristianoMafraJunior** [Engenere/BrazilFiscalReport#52]
Expansão de Suporte para Modais no DACTE
Atualmente, o DACTE oferece suporte apenas para o modal rodoviário. O objetivo desta issue é ampliar o suporte para os demais modais, conforme descrito abaixo:

- [x] Modal Rodoviário: Implementado.
- [x] Modal Aéreo: Desenvolvido na PR #50
- [x] Modal Aquaviário:  Desenvolvido na PR #51
- [x] Modal Ferroviário: Desenvolvido na PR #54 
- [x] Modal Dutoviário: Desenvolvido na PR #55 
- [x] Modal Multimodal: Desenvolvido na PR #56
